# Generated by Django 2.2.4 on 2019-09-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_all_tournaments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_tournaments',
            name='slug',
        ),
    ]
