# Generated by Django 2.2.4 on 2019-09-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_all_tournaments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_tournaments',
        ),
    ]
